native:
  interface:
    _operation: replace
    GigabitEthernet:
    - name: '1'
      description: OOB Management
      ip:
        vrf:
          forwarding:
            word: MGMT
        address:
          primary:
            address: 192.168.78.22
            mask: 255.255.255.0
      mop:
        enabled: 'false'
        sysid: 'false'
      negotiation:
        auto: 'true'
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet
    - name: '2'
      description: Link Core2-to-Core3
      ip:
        unnumbered: Loopback0
        ospf:
          network: point-to-point
          _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ospf
      mop:
        enabled: 'false'
        sysid: 'false'
      crypto:
        map:
          tag: Core2-Core1-MAP
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-crypto
      negotiation:
        auto: 'true'
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet
    - name: '3'
      description: Link Core2-to-Core4
      ip:
        unnumbered: Loopback0
        ospf:
          network: point-to-point
          _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ospf
      mop:
        enabled: 'false'
        sysid: 'false'
      crypto:
        map:
          tag: Core2-Core1-MAP
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-crypto
      negotiation:
        auto: 'true'
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet
    - name: '4'
      shutdown: null
      mop:
        enabled: 'false'
        sysid: 'false'
      negotiation:
        auto: 'true'
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet
    - name: '5'
      shutdown: null
      mop:
        enabled: 'false'
        sysid: 'false'
      negotiation:
        auto: 'true'
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet
    Loopback:
    - name: '0'
      description: Core2-id
      ip:
        address:
          primary:
            address: 1.1.1.2
            mask: 255.255.255.255
    - name: '20'
      description: BGP Advertised Loopback
      ip:
        address:
          primary:
            address: 20.20.20.1
            mask: 255.255.255.0
    - name: '200'
      description: VPN LAN Core2
      ip:
        address:
          primary:
            address: 172.168.200.1
            mask: 255.255.255.0
  _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-native
