---
ntp:
  servers:
    - ip: 192.168.78.148

bgp:
  id: '65001'
  rid: 1.1.1.4
  neighbors:
  - id: 1.1.1.1
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.2
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.3
    as: '65001'
    loopsource: '0'
  ipv4_unicast_family:
  - neighborid: 1.1.1.1
  - neighborid: 1.1.1.2
  - neighborid: 1.1.1.3
  networks:
  - number: 40.40.40.0
    mask: 255.255.255.0
ospf:
  id: '1'
  rid: 1.1.1.4
  networks:
  - ip: 1.1.1.4
    mask: 0.0.0.0
    area: '0'

ip:
  vrf:
  - name: MGMT
    description: OOB Management
  domain: cisco.com
  tftp_source_gi_int: '1'
  source_interface: GigabitEthernet1
#  static_routes:
#  - network: 172.168.200.0
#    mask: 255.255.255.0
#    fwd: 1.1.1.2
#  extended_acl:
#  - name: '111'
#    - sequence: 10
#      action: permit
#      protocol: ip
#      srcip: 172.168.100.0
#      srcmask: 0.0.0.255
#      destip: 172.168.200.0
#      destmask: 0.0.0.255

# standard_acl:
#  - name: <name>
#    - sequence: <seq number>
#      permit_ip: <ip add>
#      OR
#      deny_ip: <ip add>

interfaces:
  GigEthernet:
  - name: 1
    description: OOB Management
    vrf: MGMT
    ip: 192.168.78.24
    mask: 255.255.255.0
  - name: 2
    description: Link Core4-to-Core1
    unnumbered: Loopback0
    ospf_network: point-to-point
  - name: 3
    description: Link Core4-to-Core2
    unnumbered: Loopback0
    ospf_network: point-to-point
  - name: 4
    shutdown: yes
  - name: 5
    shutdown: yes
  Loopback:
  - name: 0
    description: Core4-id
    ip: 1.1.1.4
    mask: 255.255.255.255
  - name: 40
    description: BGP Advertised Loopback
    ip: 40.40.40.1
    mask: 255.255.255.0





