native:
  ip:
    _operation: replace
    vrf:
      name: MGMT
      description: OOB Management
    domain:
      name: cisco.com
    forward-protocol:
      protocol: nd
    ssh:
      version: '2'
    tftp:
      source-interface:
        GigabitEthernet: '1'
    access-list:
      extended:
        name: meraki-fqdn-dns
        _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-acl
    http:
      authentication:
        local: null
      server: 'true'
      secure-server: 'true'
      client:
        source-interface: GigabitEthernet1
      _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-http
  _xmlns: http://cisco.com/ns/yang/Cisco-IOS-XE-native
