Cisco-IOS-XE-native:native:
  version: '16.11'
  boot-start-marker:
  - null
  boot-end-marker:
  - null
  memory:
    free:
      low-watermark:
        processor: 80526
  call-home:
    Cisco-IOS-XE-call-home:contact-email-addr: sch-smart-licensing@cisco.com
    Cisco-IOS-XE-call-home:profile:
    - profile-name: CiscoTAC-1
      active: true
  service:
    password-encryption:
    - null
    timestamps:
      debug:
        datetime:
          msec: {}
      log:
        datetime:
          msec:
          - null
    call-home:
    - null
  platform:
    Cisco-IOS-XE-platform:console:
      output: serial
  hostname: Core4
  enable:
    secret:
      type: '9'
      secret: $9$5spXfpjbtskouk$FtW8jyp8aujkcRLZPmtsDfOoL57Qhn3FIxYt0E6HBjM
  username:
  - name: kamil
    privilege: 15
    secret:
      encryption: '9'
      secret: $9$MVrlWMdEJ4nwNk$5CLhHm9qZJh1171H0OxOTz9FwZ9qkZ4Ofg1WIXGAHf2
  ip:
    vrf:
    - name: MGMT
      description: OOB Management
    domain:
      name: ' cisco.com'
    forward-protocol:
      protocol: nd
    ssh:
      version: 2
    tftp:
      source-interface:
        GigabitEthernet: '1'
    access-list:
      Cisco-IOS-XE-acl:extended:
      - name: meraki-fqdn-dns
    Cisco-IOS-XE-http:http:
      authentication:
        local:
        - null
      server: true
      secure-server: true
      client:
        source-interface: ' GigabitEthernet1'
  interface:
    GigabitEthernet:
    - name: '1'
      description: OOB Management
      ip:
        vrf:
          forwarding:
            word: MGMT
        address:
          primary:
            address: 192.168.78.24
            mask: 255.255.255.0
      mop:
        enabled: false
        sysid: false
      Cisco-IOS-XE-ethernet:negotiation:
        auto: true
    - name: '2'
      description: Link Core4-to-Core1
      ip:
        unnumbered: Loopback0
        Cisco-IOS-XE-ospf:ospf:
          network: point-to-point
      mop:
        enabled: false
        sysid: false
      Cisco-IOS-XE-ethernet:negotiation:
        auto: true
    - name: '3'
      description: Link Core4-to-Core2
      ip:
        unnumbered: Loopback0
        Cisco-IOS-XE-ospf:ospf:
          network: point-to-point
      mop:
        enabled: false
        sysid: false
      Cisco-IOS-XE-ethernet:negotiation:
        auto: true
    - name: '4'
      shutdown:
      - null
      mop:
        enabled: false
        sysid: false
      Cisco-IOS-XE-ethernet:negotiation:
        auto: true
    - name: '5'
      shutdown:
      - null
      mop:
        enabled: false
        sysid: false
      Cisco-IOS-XE-ethernet:negotiation:
        auto: true
    Loopback:
    - name: 0
      description: Core4-id
      ip:
        address:
          primary:
            address: 1.1.1.4
            mask: 255.255.255.255
    - name: 40
      description: BGP Advertised Loopback
      ip:
        address:
          primary:
            address: 40.40.40.1
            mask: 255.255.255.0
  control-plane: {}
  login:
    on-success:
      log: {}
  multilink:
    Cisco-IOS-XE-ppp:bundle-name: authenticated
  redundancy: {}
  spanning-tree:
    Cisco-IOS-XE-spanning-tree:extend:
      system-id:
      - null
  subscriber:
    templating:
    - null
  crypto:
    Cisco-IOS-XE-crypto:pki:
      certificate:
        chain:
        - name: SLA-TrustPoint
          certificate:
          - serial: '01'
            certtype: ca
        - name: TP-self-signed-151682397
          certificate:
          - serial: '01'
            certtype: self-signed
      trustpoint:
      - id: SLA-TrustPoint
        enrollment:
          pkcs12:
          - null
        revocation-check:
        - crl
      - id: TP-self-signed-151682397
        enrollment:
          selfsigned:
          - null
        revocation-check:
        - none
        subject-name: cn=IOS-Self-Signed-Certificate-151682397
  router:
    Cisco-IOS-XE-bgp:bgp:
    - id: 65001
      bgp:
        log-neighbor-changes: true
        router-id:
          ip-id: 1.1.1.4
      neighbor:
      - id: 1.1.1.1
        remote-as: 65001
        update-source:
          Loopback: 0
      - id: 1.1.1.2
        remote-as: 65001
        update-source:
          Loopback: 0
      - id: 1.1.1.3
        remote-as: 65001
        update-source:
          Loopback: 0
      address-family:
        no-vrf:
          ipv4:
          - af-name: unicast
            ipv4-unicast:
              neighbor:
              - id: 1.1.1.1
                activate:
                - null
              - id: 1.1.1.2
                activate:
                - null
              - id: 1.1.1.3
                activate:
                - null
              network:
                with-mask:
                - number: 40.40.40.0
                  mask: 255.255.255.0
          - af-name: multicast
    Cisco-IOS-XE-ospf:ospf:
    - id: 1
      router-id: 1.1.1.4
      network:
      - ip: 1.1.1.4
        mask: 0.0.0.0
        area: 0
  license:
    udi:
      pid: CSR1000V
      sn: 9L78JUTS2FV
  line:
    console:
    - first: '0'
      stopbits: '1'
    vty:
    - first: 0
      last: 4
      login:
        local:
        - null
      transport:
        input:
          input:
          - ssh
    - first: 5
      last: 15
      login:
        local:
        - null
      transport:
        input:
          input:
          - ssh
  ntp:
    Cisco-IOS-XE-ntp:server:
      server-list:
      - ip-address: 192.168.78.148
  Cisco-IOS-XE-diagnostics:diagnostic:
    bootup:
      level: minimal
  Cisco-IOS-XE-pnp:pnp:
    profile:
    - name: pnp_cco_profile
